// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr3IldtsXg4-B6MXGtMo-rphX5UH4Pigg',
    appId: '1:516352908658:web:fdf8ee7db8a69becabd1eb',
    messagingSenderId: '516352908658',
    projectId: 'brostaky-3c17c',
    authDomain: 'brostaky-3c17c.firebaseapp.com',
    storageBucket: 'brostaky-3c17c.firebasestorage.app',
    measurementId: 'G-K58PP8LN6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABmtfxaKM-AMDaH9TktYoHp7N2fNIQt3E',
    appId: '1:516352908658:android:e14598e34f5bd5bfabd1eb',
    messagingSenderId: '516352908658',
    projectId: 'brostaky-3c17c',
    storageBucket: 'brostaky-3c17c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyxnQHtzhLFg9VUiBaxb_cfzQdp0fhwSI',
    appId: '1:516352908658:ios:2bf98133162b9927abd1eb',
    messagingSenderId: '516352908658',
    projectId: 'brostaky-3c17c',
    storageBucket: 'brostaky-3c17c.firebasestorage.app',
    androidClientId:
        '516352908658-2iv7usclo6l6o8ptkp36d792tm6rfgup.apps.googleusercontent.com',
    iosClientId:
        '516352908658-aietkrmdmgmp7mq5i5nd50bifc94ejca.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyxnQHtzhLFg9VUiBaxb_cfzQdp0fhwSI',
    appId: '1:516352908658:ios:2bf98133162b9927abd1eb',
    messagingSenderId: '516352908658',
    projectId: 'brostaky-3c17c',
    storageBucket: 'brostaky-3c17c.firebasestorage.app',
    androidClientId:
        '516352908658-2iv7usclo6l6o8ptkp36d792tm6rfgup.apps.googleusercontent.com',
    iosClientId:
        '516352908658-aietkrmdmgmp7mq5i5nd50bifc94ejca.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt1_jrZOgsYbkdCbVI4rHwXzC9ptP59hk',
    appId: '1:516352908658:web:858b5d5aec8013b9abd1eb',
    messagingSenderId: '516352908658',
    projectId: 'brostaky-3c17c',
    authDomain: 'brostaky-3c17c.firebaseapp.com',
    storageBucket: 'brostaky-3c17c.firebasestorage.app',
    measurementId: 'G-3R4P90PE2E',
  );
}
